server:
  port: 9092
  servlet:
    context-path: /manage

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/accounting_app?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
#      url: jdbc:mysql://8.153.192.39:3306/accounting_app?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true

      username: root
      password: N2v:w6e.JQ_JpiA2
      keep-alive: true
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      min-idle: 5
      max-active: 20
      time-between-eviction-runs-millis: 60000

logging:
  level:
    com.accounting: info
